### ISSUE TITLE
A question about the mutil-class focal losss

### ISSUE THREAD

**Issue by zch0414** [marcdcfischer/PUNet#1]
Hi team,

I have some concerns regarding the correctness of the focal loss implementation. It appears that the output of the NLLLoss is being used as the log probabilities, but since weights have already been assigned to the NLLLoss, the resulting outputs log_prob will resemble '- loss_weight_alpha * log_softmax'. Then exp(-log_prob) does not represent the original class probabilities because there is another term loss_weight_alpha. 

I am not sure whether I am correct. Looking forward to your answer!

**Comment by marcdcfischer** [comment]
Hi Zach, nice catch! exp(-log_prob) is wrongfully weighted that way. I'll push a quick fix.
